### ISSUE TITLE
换了关键词就不行了

### ISSUE THREAD

**Issue by shartoo** [fancoo/Crawler#1]
你这个爬虫程序换了关键词就不行了啊。然后我的疑问是为什么不适用 BeautifulSoup呢？

**Comment by fancoo** [comment]
针对1：是可行的吧，只要把data里的samples文件换成同样的数据格式就可以
针对2：最初用的BS，但是BS存在解析的bug，有时会解析不出来，于是换成了Xpath，后者感觉挺棒的，而且解析速度比BS快。

**Comment by mazzzystar** [comment]
针对1：是可行的吧，只要把data里的samples文件换成同样的数据格式就可以
针对2：最初用的BS，但是BS存在解析的bug，有时会解析不出来，于是换成了Xpath，后者感觉挺棒的，而且解析速度比BS快。

**Comment by shartoo** [comment]
哦，原来如此。我刚开始用爬虫，网络推荐BS，我再看看Xpath吧。
