### ISSUE TITLE
是不是mysql没连接上？

### ISSUE THREAD

**Issue by zhll912** [fancoo/Crawler#4]
File "e:/py/baidu/baidu_crawler.py", line 78
    print "总共：" + str(len(useful_proxies)) + 'IP可用'
              ^
SyntaxError: invalid syntax
应该如何操作，有没有详细的连接mysql的说明

**Comment by mazzzystar** [comment]
@zhll912 我刚下载到本地测试没问题，你试试用mysql新建一个数据库，库名参考config.py，然后修改config.py里的密码试试。

**Comment by zhll912** [comment]
我已经创建了数据库，同时config.py中的值也对应修改了，还是提示同样的问题，我是怀疑其它方面的问题，我用的是python3.6.1，这个影响么？另外pymysql我也安装了，还有可能有什么问题呢？

**Comment by zhll912** [comment]
数据库连接应该是可以的，我随便添加个test数据库，用另一段代码连接是可以操作的

**Comment by zhll912** [comment]
上述问题基本解决，reload(sys),这两行被我删了，会报其它错：cannot choose from an empty sequence
p这是因为我删了上边的编码就出问题了，我就在这行上加了编码设置open(keyword_dict, 'r',encoding='utf8')，不知道这个问题又如何解决，现在主要问题确定在获取不到IP地址，求指教如何获取？

**Comment by mazzzystar** [comment]
@zhll912 此程序是py2.7xx，还未在3.0以上测试过~~ 如果用pycharm不妨下双版本python，然后切换2.7试试。

**Comment by zhll912** [comment]
有没有更新3.0的计划呢？我看这个应该复杂度应该不至于有多少，只是 我初学python，否则我给你更新一个版本

**Comment by zhll912** [comment]
我在3.6下跑起来了，要不要提交上来？

**Comment by mazzzystar** [comment]
@zhll912 欢迎提交~~~
