### ISSUE TITLE
多线程的处理在哪里？

### ISSUE THREAD

**Issue by zhll912** [fancoo/Crawler#6]
我见提交中有支持多线程的版本，有具体的代码么？

**Comment by mazzzystar** [comment]
@zhll912 你可以查看PR信息，此PR并没有被merge..

**Comment by zhll912** [comment]
@fancoo 噢，为什么不合并呢？是代码还有问题？还是其它原因

**Comment by mazzzystar** [comment]
@zhll912 嗯存在一些风格上的差异。。
